name: Send Emails

on:
  schedule:
    - cron: '58 21 29 4 *'

jobs:
  send_emails:
    name: Send Emails
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Specify your Python version
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # If you have any dependencies
      
      - name: Set up environment variables
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      
      - name: Run your Python script to send emails
        run: python main.py  # Replace 'main.py' with the name of your Python script
